"use client";
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,Check,Sparkles,ExternalLink,RefreshCw} from 'lucide-react';
import type {Settings} from '@/lib/learning';
import {weekdays,dayFocus,addDays,recordKey,dateKey,type DailyRecord} from '@/lib/weekly';
import {sourceCatalog,type SourceStatus} from '@/lib/sources';
export function WeekPlanner({week,day,settings,records,busy,onDay,onWeek,onPrepare,onAI}:{week:string;day:number;settings:Settings;records:Record<string,DailyRecord>;busy:boolean;onDay:(n:number)=>void;onWeek:(s:string)=>void;onPrepare:()=>void;onAI:()=>void}){
 if(!week)return <div className="week-planner">주간 학습을 준비하고 있어요.</div>;
 const count=weekdays.filter((_,i)=>records[recordKey(settings,week,i)]?.done).length;
 return <section className="week-planner" aria-label="요일별 학습 계획"><div className="week-top"><div><span className="week-eyebrow">ONE WEEK, SEVEN SMALL STEPS</span><h2>한 주의 공부를 펼쳐요</h2></div><div className="week-control"><button disabled={busy} aria-label="이전 주" onClick={()=>onWeek(addDays(week,-7))}><ChevronLeft size={18}/></button><span>{week.slice(5).replace('-','.')} – {addDays(week,6).slice(5).replace('-','.')}</span><button disabled={busy} aria-label="다음 주" onClick={()=>onWeek(addDays(week,7))}><ChevronRight size={18}/></button></div></div><div className="days-grid">{weekdays.map((d,i)=>{const r=records[recordKey(settings,week,i)];const date=addDays(week,i);return <button disabled={busy} key={d} className={`day-card ${day===i?'day-selected':''}`} aria-pressed={day===i} onClick={()=>onDay(i)}><span className="day-date">{d}요일 <small>{date.slice(5).replace('-','.')}</small></span><strong>{dayFocus[i]}</strong><span className="day-state">{r?.done?<><Check size={14}/>학습 완료</>:r?.questions?`${r.source.startsWith('AI')?'AI':'기본'} ${r.questions.length}문제 · ${Object.keys(r.answers).length}개 풀이`:'아직 준비 전'}</span>{date===dateKey()&&<span className="today-dot">오늘</span>}</button>})}</div><div className="week-bottom"><span>{count}/7일 완료 · 설정한 과목 기준</span><div><button disabled={busy} onClick={onPrepare}>7일 기본 문제 준비</button><button disabled={busy} className="week-ai" onClick={onAI}><Sparkles size={16}/>{busy?'문제 준비 중…':'7일 AI 문제 만들기'}</button></div></div><p className="week-caption">문제와 풀이 기록은 이 브라우저에 저장됩니다. 기본 문제에는 반복 복습이 포함됩니다. 7일 AI 출제는 최대 7회 요청하며 API 사용료가 발생할 수 있습니다.</p></section>
}
export function SourcesPanel(){const [sources,setSources]=useState<any[]>(sourceCatalog.map(x=>({...x,status:'snapshot'}))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/sources');if(!r.ok)throw Error();const data:any=await r.json();setSources(data.sources)}catch{setError('원문 연결 상태를 확인하지 못했습니다. 아래에는 마지막으로 검토한 자료를 표시합니다.')}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 return <section className="info sources-panel"><div className="source-heading"><div><span className="pill">출처가 있는 공부</span><h2>EBS · 교육과정 자료실</h2></div><button onClick={refresh} disabled={busy}><RefreshCw size={16}/>{busy?'확인 중…':'원문 연결 확인'}</button></div><p>2026년 EBS 공개 안내와 교육부 교육과정 고시를 출제 참고자료로 사용합니다. AI 출제 시 원문을 다시 읽고, 연결에 실패하면 확인 날짜가 표시된 요약을 사용합니다.</p><div className="source-grid">{sources.map(s=><article key={s.id}><span>{s.publisher}</span><h3>{s.title}</h3><p>{s.summary}</p><div className="source-status">{s.status==='live'?'원문 읽기 성공':'검토한 요약 사용'} · {s.checkedAt.slice(0,10)}</div><a href={s.url} target="_blank" rel="noreferrer">공식 자료 열기<ExternalLink size={15}/></a></article>)}</div>{error&&<p role="alert" className="notice">{error}</p>}<div className="source-scope"><h3>어떤 내용을 반영하나요?</h3><p>EBS의 대상 학년·교재 구성과 교육부의 교과 구분·적용 시점을 참고하여 자체 문항을 만듭니다. 공식 성취기준 전체나 EBS 교재의 문제 원문을 제공하는 서비스는 아니며, EBS·교육부의 공식 검수 또는 제휴를 의미하지 않습니다.</p><p>원문 연결 결과는 최대 6시간 재사용합니다. 새로운 고시의 자동 발견과 모든 첨부파일의 해석은 지원하지 않으므로, 학습 범위는 학교 진도와 원문을 함께 확인해 주세요.</p></div></section>
}
export {AIConnection} from "./ai-connection";
