"use client";
import {useEffect,useState} from 'react';
import {aiFetch} from '@/lib/ai-client';
import {BookOpen,ArrowUpRight,ArrowRight,Printer,Sparkles,Check,SlidersHorizontal,Sun,Calculator,Languages,FlaskConical,Globe,Leaf,ChevronLeft,ChevronRight,RotateCcw,CheckCircle2} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {topics,subjects,type Question,type Settings} from '@/lib/learning';
import {useWeekly} from '@/lib/use-weekly';
import {weekdays,dayFocus,recordKey,addDays} from '@/lib/weekly';
import {WeekPlanner,SourcesPanel,AIConnection} from '@/components/learning-panels';
const icons:Record<string,typeof BookOpen>={수학:Calculator,국어:BookOpen,영어:Languages,사회:Globe,과학:FlaskConical,통합:Leaf};
const names=['차근차근','탄탄하게','도전하기'];
const defaults:Settings={grade:3,subject:'수학',count:10,level:2,topic:0};
function Picker({value,items,onChange,label}:{value:string;items:string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [s,setS]=useState(defaults),[view,setView]=useState('today'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[today,setToday]=useState(''),[ready,setReady]=useState(false);
 const weekly=useWeekly(s,ready),rec=weekly.record;
 const qs=rec?.questions||[],answers=rec?.answers||{},index=rec?.index||0,done=rec?.done||false,source=rec?.source||'기본 연습 · 자체 제작';
 const setAnswers=(next:any)=>weekly.update({answers:typeof next==='function'?next(answers):next});
 const setIndex=(next:any)=>weekly.update({index:typeof next==='function'?next(index):next});
 const setDone=(done:boolean)=>weekly.update({done});
 useEffect(()=>{setToday(new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Seoul'}));try{const p=JSON.parse(localStorage.getItem('haru-settings')||'null');if(p&&Number.isInteger(p.grade)&&p.grade>=1&&p.grade<=6&&[5,10,15,20].includes(p.count)&&[1,2,3].includes(p.level)&&subjects(p.grade).includes(p.subject))setS({...p,topic:0});}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('haru-settings',JSON.stringify(s))}catch{}},[s,ready]);
 const change=(patch:Partial<Settings>)=>{if(busy)return;setS(v=>({...v,...patch}));setView('today');setNotice('')};
 function start(){weekly.ensure();setView('study')}
 async function ai(all=false){
  if(busy||!weekly.week)return;setBusy(true);setNotice('');const base={...s},week=weekly.week,day=weekly.day;
  const excluded=Object.entries(weekly.records).filter(([k])=>k.startsWith(week+'|')).flatMap(([,r])=>r.questions.map(q=>q.prompt+' '+q.passage));
  let made=0,skipped=0;try{
   for(const targetDay of all?[0,1,2,3,4,5,6]:[day]){
    const key=recordKey(base,week,targetDay),existing=weekly.records[key];
    if(existing&&(Object.keys(existing.answers).length>0||existing.source.startsWith('AI'))){skipped++;continue;}
    setNotice(weekdays[targetDay]+'요일 문제를 만들고 있어요. '+(all?'('+String(made+1)+'/7)':''));
    const r=await aiFetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...base,day:targetDay,week,exclude:excluded.filter(x=>x.length<=3000).slice(-140).reduceRight((a:string[],x:string)=>a.join('').length+x.length<=20000?[x,...a]:a,[])}),signal:AbortSignal.timeout(90000)});
    const data:any=await r.json();if(!r.ok)throw new Error(data.error||'문제를 만들지 못했습니다. 다시 시도해 주세요.');
    weekly.put(key,data.questions,'AI 생성 · 공개 자료 참고',data.sources);excluded.push(...data.questions.map((q:Question)=>q.prompt+' '+q.passage));made++;
   }
   setNotice(made+'일의 AI 문제를 준비했습니다.'+(skipped?' 이미 준비됐거나 풀이 중인 '+skipped+'일은 유지했습니다.':''));
   if(!all&&made>0)setView('study');
  }catch(e){setNotice((made?made+'일은 저장했습니다. ':'')+(e instanceof Error?e.message:'연결을 확인해 주세요.'))}finally{setBusy(false)}
 }
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:'configure_daily_learning',description:'학년, 과목, 문제 수, 난이도를 설정합니다. 학습을 시작하거나 답을 제출하지 않습니다.',inputSchema:{type:'object',properties:{grade:{type:'integer',minimum:1,maximum:6},subject:{type:'string'},count:{type:'integer',enum:[5,10,15,20]},level:{type:'integer',minimum:1,maximum:3}},required:['grade','subject','count','level'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(p:any)=>{if(!p||![1,2,3,4,5,6].includes(p.grade)||!subjects(p.grade).includes(p.subject)||![5,10,15,20].includes(p.count)||![1,2,3].includes(p.level))throw new Error('학습 설정 값이 올바르지 않습니다.');change({...p,topic:0});return {configured:true,...p}}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[busy]);
 const list=topics(s.grade,s.subject),q=qs[index],score=qs.filter((q,i)=>answers[i]===q.answer).length;
 function print(){weekly.ensure();setView('print')}
 return <div className="app"><header className="top"><a href="/" className="brand"><span className="brand-mark"><BookOpen size={23}/></span>하루한뼘<span className="brand-small">매일, 스스로 자라는 공부</span></a><button className="parent" onClick={()=>{setView('today');setTimeout(()=>document.getElementById('settings')?.scrollIntoView({behavior:'smooth'}),50)}}><SlidersHorizontal size={17}/>학습 설정</button><span className="avatar">나</span></header>
 <div className="page"><div className="eyebrow"><span>MY LITTLE STUDY ROOM</span><span>{today}</span></div><div className="heading"><div><h1>오늘도 한 뼘, 자라볼까?</h1><p>작은 공부가 모여, 큰 자신감이 돼요.</p></div><span className="grade-tag">초등 {s.grade}학년 <Sun size={19}/></span></div>
 <Tabs value={view==='study'||view==='print'?'today':view} onValueChange={setView}><TabsList className="navtabs"><TabsTrigger value="today">오늘의 학습</TabsTrigger><TabsTrigger value="curriculum">학년별 교육과정</TabsTrigger><TabsTrigger value="sources">학습 자료</TabsTrigger><TabsTrigger value="connection">AI 연결</TabsTrigger><TabsTrigger value="guide">이용 안내</TabsTrigger></TabsList></Tabs>
 {view==='today'&&<WeekPlanner week={weekly.week} day={weekly.day} settings={s} records={weekly.records} busy={busy} onDay={d=>{weekly.setDay(d);setNotice('')}} onWeek={w=>{weekly.setWeek(w);setNotice('')}} onPrepare={()=>{weekly.prepareWeek();setNotice('월요일부터 일요일까지 기본 문제를 준비했습니다.')}} onAI={()=>ai(true)}/>}
 {weekly.storageError&&<p className="notice" role="alert">{weekly.storageError}</p>}
 {notice&&<p className="notice global-notice" role="status">{notice}</p>}
 {view==='sources'&&<SourcesPanel/>}
 {view==='connection'&&<AIConnection busy={busy} onGenerate={()=>ai(false)}/>}
 {view==='today'&&<div className="workspace"><section><div className="intro"><div><span className="pill">{weekdays[weekly.day]}요일 · {dayFocus[weekly.day]}</span><h2>많이보다 꾸준히.<br/>{weekdays[weekly.day]}요일은 <em>{s.count}문제</em>면 충분해요.</h2><p>내 속도에 맞춰 차근차근 시작해요.</p></div><div className="daily-counter"><span>TODAY’S GOAL</span><strong>{s.count}<small>문제</small></strong><span>하루 한 번의 작은 성취</span></div></div>
 <div className="section-title"><h2>어떤 과목을 공부할까요?</h2><span>01 / 과목 선택</span></div><div className="subjects">{subjects(s.grade).map((sub,i)=>{const Icon=icons[sub];return <button key={sub} onClick={()=>change({subject:sub,topic:0})} className={`subject tone-${i} ${s.subject===sub?'chosen':''}`} aria-pressed={s.subject===sub}><span className="subject-icon"><Icon size={24}/></span><strong>{sub}</strong><span>{sub==='수학'?'생각하는 힘':sub==='국어'?'읽고 표현하는 힘':sub==='영어'?'세상과 말하는 힘':sub==='과학'?'발견하는 즐거움':sub==='사회'?'함께 사는 세상':'일상 속 배움'}</span>{s.subject===sub&&<Check size={17} className="subject-check"/>}</button>})}</div>
 <div className="section-title"><h2>오늘의 학습 주제</h2><span>02 / 주제 선택</span></div><div className="unit-list">{list.map((t,i)=><button key={t} className={s.topic===i?'unit selected':'unit'} onClick={()=>change({topic:i})}><span className="unit-no">{String(i+1).padStart(2,'0')}</span><span><strong>{t}</strong><small>초등 {s.grade}학년 · {s.subject}</small></span><span className="unit-end">{s.topic===i?<CheckCircle2 size={22}/>:<ChevronRight size={20}/>}</span></button>)}</div><p className="footnote">기본 연습: 수학은 난이도별 계산 연습, 다른 과목은 기초 문제를 제공합니다. 학년·난이도별 확장 출제는 AI 연결이 필요합니다.<br/>학습 주제는 교육과정의 영역을 참고한 구성입니다. 학교·교과서별 진도는 다를 수 있어요.</p>
 </section><aside id="settings"><div className="settings"><div className="settings-title"><h2>우리 아이에게 맞게</h2><SlidersHorizontal size={20}/></div><p>부담 없이, 꾸준히 할 수 있는 만큼.</p><label>학년</label><Picker label="학년" value={`초등학교 ${s.grade}학년`} items={[1,2,3,4,5,6].map(n=>`초등학교 ${n}학년`)} onChange={v=>{const g=Number(v.match(/\d/)![0]);change({grade:g,subject:subjects(g).includes(s.subject)?s.subject:'수학',topic:0})}}/><label>하루 문제 수 <span>선택한 과목 기준</span></label><RadioGroup className="count-grid" value={String(s.count)} onValueChange={v=>change({count:Number(v)})}>{[5,10,15,20].map(n=><label className={s.count===n?'active':''} key={n}><RadioGroupItem value={String(n)}/>{n}<small>문제</small></label>)}</RadioGroup><label>학습 난이도</label><RadioGroup className="levels" value={String(s.level)} onValueChange={v=>change({level:Number(v)})}>{names.map((n,i)=><label className={s.level===i+1?'active':''} key={n}><RadioGroupItem value={String(i+1)}/><span className="level-bars">{'▮'.repeat(i+1)}</span><span><strong>레벨 {i+1} · {n}</strong><small>{['개념부터 천천히 익혀요','배운 내용을 연습해요','한 번 더 생각해 봐요'][i]}</small></span></label>)}</RadioGroup><div className="summary"><span>{s.subject} · {list[s.topic]}</span><strong>{s.count}문제 / 레벨 {s.level}</strong></div><button className="primary" disabled={busy||!weekly.loaded} onClick={start}>{weekdays[weekly.day]}요일 {rec?.done?'결과 보기':Object.keys(answers).length?'이어서 학습':'학습 시작'}<ArrowRight size={19}/></button><button className="secondary" disabled={busy||!weekly.loaded} onClick={print}><Printer size={17}/>학습지로 출력하기</button><small className="saved"><Check size={14}/>요일별 문제와 풀이도 자동 저장돼요</small></div><div className="ai-card"><Sparkles size={22}/><div><h3>새로운 문제로 한 걸음 더</h3><p>선택한 학년과 주제에 맞춰<br/>AI에게 문제를 부탁해 보세요.</p><button onClick={()=>ai(false)} disabled={busy}>{busy?'문제를 만들고 있어요…':'AI 맞춤 문제 만들기'}<ArrowUpRight size={17}/></button></div></div></aside></div>}
 {view==='study'&&q&&<section className="study">{rec?.references&&<details className="question-sources"><summary>이 문제를 만들 때 참고한 자료</summary>{rec.references.map(x=><p key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a> · {x.checkedAt.slice(0,10)} · {x.status==='live'?'원문 확인':'확인된 요약'}</p>)}<p>AI 생성 문제 · 보호자의 정답·해설 검토를 권장합니다.</p></details>}<div className="study-top"><button onClick={()=>setView('today')}><ChevronLeft size={18}/>학습실</button><span>{weekly.week&&addDays(weekly.week,weekly.day)} ({weekdays[weekly.day]}) · {s.grade}학년 {s.subject} · {list[s.topic]}</span><button onClick={print}><Printer size={18}/>출력</button></div>{!done?<><div className="progress-title"><span>{source} · {weekdays[weekly.day]}요일</span><strong>{index+1} <small>/ {qs.length}</small></strong></div><Progress value={(index+1)/qs.length*100}/><div className="question"><span className="question-number">QUESTION {String(index+1).padStart(2,'0')}</span><h2>{q.prompt}</h2>{q.passage&&<p className="passage">{q.passage}</p>}<RadioGroup value={answers[index]||''} onValueChange={v=>setAnswers((a:Record<number,string>)=>({...a,[index]:v}))} className="choices">{q.choices.map((c,i)=><label key={c} className={answers[index]===c?'picked':''}><RadioGroupItem value={c}/><span>{i+1}</span>{c}</label>)}</RadioGroup></div><div className="question-actions"><button disabled={index===0} onClick={()=>setIndex((i:number)=>i-1)}><ChevronLeft size={18}/>이전 문제</button><span>{Object.keys(answers).length} / {qs.length}문제 풀었어요</span><button className="primary" disabled={!answers[index]} onClick={()=>index<qs.length-1?setIndex((i:number)=>i+1):setDone(true)}>{index===qs.length-1?'채점하고 해설 보기':'다음 문제'}<ArrowRight size={18}/></button></div></>:<><div className="result"><CheckCircle2 size={44}/><h2>{weekdays[weekly.day]}요일의 한 뼘을 채웠어요!</h2><p>{qs.length}문제 중 <strong>{score}문제</strong> 정답 · {Math.round(score/qs.length*100)}점</p><button className="primary" onClick={()=>{setAnswers({});setIndex(0);setDone(false)}}><RotateCcw size={17}/>다시 풀어보기</button></div>{qs.map((item,i)=><div className={`review ${answers[i]===item.answer?'correct':''}`} key={i}><strong>{answers[i]===item.answer?'✓':'다시 생각해 봐요'} · {i+1}번</strong><h3>{item.prompt}</h3>{item.passage&&<p>{item.passage}</p>}<p>내 답: {answers[i]||'미응답'} <b>정답: {item.answer}</b></p><p>{item.explanation}</p></div>)}</>}</section>}
 {view==='print'&&<section className="print-preview"><div className="print-tools"><div><h2>종이 위에서도, 한 뼘 더</h2><p>A4 학습지와 별도 정답지를 함께 준비했어요.</p></div><button className="primary" onClick={()=>window.print()}><Printer size={18}/>인쇄 / PDF 저장</button><button onClick={()=>setView('today')}>돌아가기</button></div><div className="worksheet"><div className="paper-head"><strong>하루한뼘</strong><span>{s.grade}학년 · {s.subject} · 레벨 {s.level}</span></div><h1>{list[s.topic]}</h1><p>날짜: {weekly.week&&addDays(weekly.week,weekly.day)} ({weekdays[weekly.day]})　이름: ________________</p><p className="paper-source">{source} · {qs.length}문제</p>{rec?.references&&<p className="paper-source">참고: {rec.references.map(x=>x.title+' ('+x.checkedAt.slice(0,10)+')').join(' · ')}</p>}{qs.map((x,i)=><div className="paper-question" key={i}><h3>{i+1}. {x.prompt}</h3>{x.passage&&<p>{x.passage}</p>}<p>{x.choices.map((c,n)=>`${n+1}) ${c}`).join('　　')}</p><div className="answer-space">답: ________________</div></div>)}<div className="answer-sheet"><h2>정답과 해설</h2>{qs.map((x,i)=><div key={i}><strong>{i+1}. {x.answer}</strong><p>{x.explanation}</p></div>)}</div></div></section>}
 {view==='curriculum'&&<section className="info"><span className="pill">교육과정 안내</span><h2>학년에 맞는 배움의 길</h2><p>2022 개정 교육과정은 2026년 초등학교 전 학년에 적용됩니다. 아래는 학습 설계를 위한 주제 요약이며 공식 성취기준 전체를 수록한 자료는 아닙니다.</p><a href="https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&boardSeq=93458&lev=0&searchType=null" target="_blank" rel="noreferrer">교육부 교육과정 고시 원문 보기 ↗</a><div className="curriculum-grid">{[1,2,3,4,5,6].map(g=><article key={g}><span>GRADE 0{g}</span><h3>{g}학년</h3>{subjects(g).map(sub=><p key={sub}><strong>{sub}</strong> {topics(g,sub).join(' · ')}</p>)}<button onClick={()=>{change({grade:g,subject:'수학',topic:0});setView('today')}}>{g}학년 학습하기<ArrowRight size={17}/></button></article>)}</div><p className="notice">기본 연습문제는 일부 주제를 지원합니다. EBS·교육부의 공개 안내를 AI 출제에 참조합니다. 공식 성취기준 전체 매핑은 포함하지 않습니다. 출처와 원문 연결 상태는 학습 자료에서 확인하세요.</p></section>}
 {view==='guide'&&<section className="info"><h2>오늘의 공부, 이렇게 시작해요</h2><div className="guide-grid">{[['01','나에게 맞게 정해요','학년, 과목, 주제, 하루 문제 수와 난이도를 선택해요. 설정은 현재 브라우저에 저장됩니다.'],['02','생각하고 풀어봐요','기본 연습문제는 바로 풀 수 있어요. 마지막 문제까지 풀면 채점 결과와 해설을 확인해요.'],['03','종이로도 공부해요','학습지를 출력하거나 인쇄 창에서 PDF로 저장해요. 정답지는 새 페이지에서 시작합니다.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><h3>AI 출제 안내</h3><p>월요일부터 일요일까지 기본 문제를 준비할 수 있습니다. AI 연결 화면에서 상태를 확인한 뒤 하루 또는 7일 AI 출제를 이용하세요. 이미 AI 문제가 있거나 풀이를 시작한 날은 유지합니다. AI 문제에는 오류가 있을 수 있어 보호자의 검토가 필요합니다.</p><h3>저장 안내</h3><p>학습 설정과 최근 100개 학습 세트를 이 기기에 저장합니다. 요일별 문제·풀이·결과도 이 브라우저에 저장되며 다른 기기로 동기화되지는 않습니다. 자녀 이름이나 개인정보는 입력하지 않아도 됩니다.</p></section>}
 <footer><span className="footer-brand">하루한뼘</span><span>비교하지 않고, 내 속도로.</span><span>초등 1–6학년 자율학습</span></footer></div></div>;
}

