"use client";
import {useEffect,useState,type CSSProperties} from 'react';
import {ArrowRight,BookOpen,Check,Plus,ShieldCheck,Star,Trophy} from 'lucide-react';
import {StudyCompanion,studyThemes} from '@/components/study-theme';
import {createProfile,importLegacyLearning,readProfiles,readProfileSummary,saveProfiles,type LearnerProfile,type ProfileTheme} from '@/lib/profiles';

const themeIds=Object.keys(studyThemes) as ProfileTheme[];
const cardStyle=(theme:ProfileTheme)=>({'--profile-accent':studyThemes[theme].accent} as CSSProperties);

export function ProfileGate({onEnter}:{onEnter:(profile:LearnerProfile)=>void}){
 const [profiles,setProfiles]=useState<LearnerProfile[]>([]),[name,setName]=useState(''),[grade,setGrade]=useState(3),[theme,setTheme]=useState<ProfileTheme>('forest'),[ready,setReady]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const items=readProfiles();setProfiles(items);saveProfiles(items);setReady(true)},[]);
 function add(){const clean=name.trim().replace(/\s+/g,' ');if(!clean){setMessage('사용자 이름을 입력해 주세요.');return}if(profiles.length>=8){setMessage('사용자는 최대 8명까지 추가할 수 있어요.');return}const profile=createProfile(clean,grade,theme),next=[...profiles,profile];saveProfiles(next);if(profiles.length===0)importLegacyLearning(profile.id);setProfiles(next);setName('');setMessage('');onEnter(profile)}
 if(!ready)return <main className="profile-gate"><p className="profile-loading">사용자 정보를 불러오고 있어요…</p></main>;
 return <main className="profile-gate"><div className="profile-shell"><header className="profile-hero"><div className="profile-logo"><span className="brand-mark"><BookOpen size={25}/></span><strong>하루한뼘</strong></div><span className="profile-kicker">MY STUDY PROFILE</span><h1>오늘 공부할 친구는<br/><em>누구인가요?</em></h1><p>내 프로필로 들어가면 점수와 학습 기록이 그대로 이어져요.</p><span className="profile-safe"><ShieldCheck size={15}/>이 브라우저에만 안전하게 저장돼요</span></header>
  <section className="profile-entry"><div className="profile-entry-head"><div><span>LEARNER PROFILES</span><h2>내 프로필을 선택해요</h2></div><small>{profiles.length}/8명</small></div>
   {profiles.length>0?<div className="profile-grid">{profiles.map(profile=>{const summary=readProfileSummary(profile.id),buddy=studyThemes[profile.theme];return <button key={profile.id} className="profile-card" style={cardStyle(profile.theme)} onClick={()=>onEnter(profile)} aria-label={`${profile.name}, 초등 ${profile.grade}학년 프로필로 입장`}><span className="profile-card-grade">초등 {profile.grade}학년</span><span className="profile-character"><StudyCompanion theme={profile.theme} decorative/></span><span className="profile-card-copy"><small>{buddy.name}와 공부하는</small><strong>{profile.name}</strong></span><span className="profile-points"><Star size={15}/>{summary.points.toLocaleString()}점</span><span className="profile-stats"><span><Trophy size={13}/>{summary.sessions}회 학습</span><span>정답률 {summary.accuracy}%</span></span><span className="profile-enter">이 프로필로 시작하기 <ArrowRight size={16}/></span></button>})}</div>:<div className="profile-empty"><StudyCompanion theme="forest" decorative/><div><strong>아직 등록된 사용자가 없어요</strong><p>아래에서 첫 번째 학습 프로필을 만들어 주세요.</p></div></div>}
   <form className="profile-add" onSubmit={e=>{e.preventDefault();add()}}><div className="profile-add-title"><span><Plus size={18}/></span><div><small>NEW LEARNER</small><h2>새 사용자 프로필 만들기</h2></div></div><label htmlFor="learner-name">사용자 이름</label><input id="learner-name" value={name} onChange={e=>setName(e.target.value)} maxLength={12} placeholder="아이 이름 또는 별명" autoComplete="off"/>
    <fieldset className="profile-grade"><legend>학년 선택</legend><div>{[1,2,3,4,5,6].map(value=><button type="button" key={value} aria-pressed={grade===value} onClick={()=>setGrade(value)}><strong>{value}</strong><small>학년</small></button>)}</div></fieldset>
    <fieldset className="profile-buddy"><legend>함께 공부할 캐릭터</legend><div>{themeIds.map(id=>{const buddy=studyThemes[id];return <button type="button" key={id} aria-pressed={theme===id} onClick={()=>setTheme(id)} style={cardStyle(id)}><StudyCompanion theme={id} decorative/><span><strong>{buddy.name}</strong><small>{buddy.label}</small></span>{theme===id&&<Check size={16}/>}</button>})}</div></fieldset>
    {message&&<p className="profile-error" role="alert">{message}</p>}<button className="profile-create" disabled={!name.trim()||profiles.length>=8}><Plus size={18}/>프로필 만들고 시작하기</button><p className="profile-local-note">프로필별 학년·점수·문제 풀이 기록을 따로 관리합니다.</p></form>
  </section></div></main>
}

export function LearningDashboard({profile,summary,onSwitch}:{profile:LearnerProfile;summary:ReturnType<typeof readProfileSummary>;onSwitch:()=>void}){
 const progress=summary.points%500,buddy=studyThemes[profile.theme];
 return <section className="learner-dashboard"><div className="learner-name"><span className="dashboard-buddy"><StudyCompanion theme={profile.theme} decorative/></span><div><small>초등 {profile.grade}학년 · {buddy.name}와 함께</small><h2>{profile.name}의 학습 기록</h2></div><button onClick={onSwitch}>사용자 변경</button></div><div className="score-cards"><article><small>누적 점수</small><strong>{summary.points.toLocaleString()}<em>점</em></strong></article><article><small>완료한 학습</small><strong>{summary.sessions}<em>회</em></strong></article><article><small>맞힌 문제</small><strong>{summary.correct}<em>문제</em></strong></article><article><small>정답률</small><strong>{summary.accuracy}<em>%</em></strong></article></div><div className="level-progress"><span>LEVEL {summary.level}</span><div><i style={{width:`${progress/5}%`}}/></div><small>다음 레벨까지 {(500-progress).toLocaleString()}점</small></div><p>문제를 풀면 2점, 정답이면 8점이 더해지고 학습 완료 시 10점을 받아요. 같은 학습은 한 번만 적립됩니다.</p></section>
}
