export type Settings={grade:number;subject:string;count:number;level:number;topic:number};
export type Question={prompt:string;passage:string;choices:string[];answer:string;explanation:string};
export const subjects=(g:number)=>g<3?['수학','국어','통합']:['수학','국어','영어','사회','과학'];
export function topics(g:number,s:string):string[]{if(s==='수학')return [['덧셈과 뺄셈','수의 크기 비교'],['두 자리 수의 계산','곱셈구구'],['곱셈','나눗셈'],['큰 수의 계산','분모가 같은 분수'],['약수와 배수','분수의 덧셈'],['비와 비율','소수의 나눗셈']][g-1];if(s==='국어')return g<3?['내용 이해하기','낱말과 행동']:g<5?['내용 이해하기','원인과 결과']:['주장과 근거','추론하며 읽기'];if(s==='영어')return ['낱말과 의미','문장 속 낱말'];if(s==='과학')return ['생물의 특징','물질의 상태'];if(s==='사회')return ['우리 지역과 공동체','생활과 경제'];return ['안전한 생활','서로 돕는 생활']}
function shuffle<T>(a:T[],random:()=>number=Math.random){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function question(prompt:string,answer:string,others:string[],explanation:string,passage=''):Question{return {prompt,answer,choices:shuffle([...new Set([answer,...others])].slice(0,4)),explanation,passage}}
const words=[['apple','사과'],['book','책'],['school','학교'],['friend','친구'],['tree','나무'],['dog','개'],['cat','고양이'],['bird','새'],['flower','꽃'],['house','집'],['pencil','연필'],['desk','책상'],['chair','의자'],['bag','가방'],['rabbit','토끼'],['car','자동차'],['bus','버스'],['orange','오렌지'],['elephant','코끼리'],['umbrella','우산']];
const banks:Record<string,string[][][]>={
과학:[[['식물의 뿌리가 하는 일','물 흡수','소리 내기','사냥하기','날아가기'],['곤충의 다리 수','6개','2개','4개','8개'],['식물이 자라는 데 필요한 것','물과 빛','플라스틱','장난감','연필'],['생태계에서 생산자인 생물','풀','토끼','여우','매'],['새의 몸을 덮고 있는 것','깃털','비늘','껍데기','잎'],['물고기가 물속에서 숨 쉬는 기관','아가미','날개','지느러미','꼬리'],['씨앗이 싹틀 때 필요한 조건','알맞은 온도와 물','반드시 얼음','소금물','아주 높은 열'],['초식 동물의 먹이','식물','플라스틱','돌','유리'],['식물이 빛을 이용해 양분을 만드는 작용','광합성','증발','융해','응고'],['지렁이가 주로 사는 곳','흙 속','바다 깊은 곳','하늘','얼음 속']], [['얼음이 녹아 된 것','물','돌','모래','나무'],['물이 얼어 된 것','얼음','수증기','공기','흙'],['수증기의 상태','기체','고체','액체','금속'],['담는 그릇에 따라 모양이 변하는 물질','물','돌','얼음','나무토막'],['소금물을 증발시켰을 때 남는 것','소금','설탕','모래','얼음'],['물이 수증기로 변하는 현상','기화','응고','녹음','침전'],['수증기가 물방울로 변하는 현상','응결','증발','응고','연소'],['고체의 예','돌','물','공기','수증기'],['물에 녹는 물질','설탕','모래','자갈','철 못'],['물에 잘 녹지 않는 물질','모래','설탕','소금','베이킹소다']]],
사회:[[['지역에서 책을 빌리는 곳','도서관','소방서','경찰서','보건소'],['화재를 진압하는 기관','소방서','도서관','은행','우체국'],['편지와 소포를 보내는 곳','우체국','소방서','학교','놀이터'],['시민의 안전과 질서를 지키는 기관','경찰서','은행','도서관','미술관'],['다른 사람의 의견을 듣는 태도','존중하며 듣기','무시하기','말 끊기','화를 내기'],['공동체의 약속을 정하는 방법','함께 의논하기','한 명이 마음대로 정하기','다른 의견 금지하기','의논하지 않기'],['공공장소에서 지킬 행동','다른 사람 배려하기','큰 소리 내기','쓰레기 버리기','줄 무시하기'],['지역의 옛 물건과 유물을 살펴볼 곳','박물관','소방서','은행','주차장'],['민주적인 의사 결정에 필요한 것','자유롭게 의견 나누기','다른 사람 협박하기','소수 의견 무시하기','투표 강요하기'],['지도를 볼 때 방향을 알려주는 것','방위표','광고','가격표','시간표']], [['물건을 만드는 활동','생산','소비','낭비','휴식'],['물건과 서비스를 사용하는 활동','소비','생산','재배','제조'],['물건을 사기 전에 할 일','필요성과 가격 비교','가장 비싼 것 고르기','모두 사기','광고만 믿기'],['돈을 아끼는 습관','계획해서 사기','충동구매','물건 버리기','가격 무시하기'],['환경을 생각하는 소비','오래 쓸 물건 고르기','일회용품만 쓰기','멀쩡한 것 버리기','포장만 보고 사기'],['물건을 다시 사용하는 행동','장바구니 재사용','일회용 봉투 버리기','새 컵만 쓰기','책 찢기'],['가게에서 물건 값으로 내는 것','돈','영수증','광고','가격표'],['미래를 위해 돈을 모으는 활동','저축','낭비','충동구매','과소비'],['물건을 사고 받은 내역을 보여주는 것','영수증','일기','지도','시간표'],['한정된 용돈으로 선택할 때 고려할 것','꼭 필요한 정도','친구에게 자랑하기','가장 화려한 포장','광고 횟수']]],
통합:[[['길을 건널 때 할 일','멈추고 양쪽 살피기','눈 감고 뛰기','휴대폰 보기','차 사이로 뛰기'],['밥 먹기 전에 할 일','손 씻기','손에 흙 묻히기','신발 만지기','바닥에 눕기'],['비 오는 날 걷는 방법','천천히 걷기','미끄러운 길에서 뛰기','차도로 걷기','눈 가리기'],['뜨거운 냄비를 보았을 때','어른에게 도움 청하기','맨손으로 잡기','안고 뛰기','장난감으로 쓰기'],['낯선 사람이 따라오라고 할 때','믿을 수 있는 어른에게 알리기','따라가기','차에 타기','집 주소 말하기'],['자동차에 탔을 때 할 일','안전띠 매기','창밖으로 손 내밀기','운전 방해하기','좌석에서 뛰기'],['물놀이할 때 할 일','어른과 함께하기','혼자 깊은 곳 가기','친구 밀기','물에 갑자기 뛰어들기'],['계단에서 지킬 일','난간 잡고 천천히 이동','뛰어내리기','뒤로 걷기','친구 밀기'],['모르는 약을 발견했을 때','먹지 않고 어른에게 알리기','맛보기','친구에게 주기','사탕처럼 먹기'],['놀이터에서 지킬 약속','차례 지키기','새치기','밀치기','위험하게 뛰기']], [['친구가 넘어졌을 때','괜찮은지 물어보기','웃기','모른 척하기','더 밀기'],['친구 물건을 쓰기 전에','허락 구하기','몰래 가져가기','숨기기','던지기'],['잘못했을 때 할 일','사과하기','화내기','숨기기','남 탓하기'],['함께 쓰는 교실에서 할 일','함께 정리하기','어지르기','쓰레기 두기','책상 차기'],['친구가 말할 때 할 일','끝까지 듣기','소리 지르기','말 끊기','등 돌리기'],['도움을 받았을 때 할 말','고마워','싫어','저리 가','모른 척할 거야'],['친구와 다투었을 때','이야기로 해결하기','때리기','물건 빼앗기','욕하기'],['새 친구를 만났을 때','반갑게 인사하기','놀리기','따돌리기','모른 척하기'],['물건을 나눠 쓸 때','서로 차례 정하기','독차지하기','숨기기','망가뜨리기'],['아픈 친구를 대하는 태도','걱정하고 배려하기','놀리기','소문 내기','억지로 뛰게 하기']]]};
export function generate(s:Settings,random:()=>number=Math.random,day=0):Question[]{const question=(prompt:string,answer:string,others:string[],explanation:string,passage=''):Question=>({prompt,answer,choices:shuffle([...new Set([answer,...others])].slice(0,4),random),explanation,passage});const out:Question[]=[];const seen=new Set<string>();let tries=0;while(out.length<s.count&&tries++<5000){const i=tries,a=2+Math.floor(random()*8*s.level),b=2+Math.floor(random()*8),name=['민서','지우','하준','서윤','유진'][i%5];let q:Question;
if(s.subject==='수학'){let ans=0,p='',ex='';if(s.grade===1){const x=1+Math.floor(random()*(s.level===1?9:40)),y=1+Math.floor(random()*(s.level===1?9:30));if(s.topic===1){if(x===y)continue;ans=Math.max(x,y);p=`${x}와 ${y} 중 더 큰 수는 무엇인가요?`;ex=`${ans}이 더 큰 수예요.`}else{const minus=i%2===0;ans=minus?Math.abs(x-y):x+y;p=minus?`${Math.max(x,y)} − ${Math.min(x,y)} = ?`:`${x} + ${y} = ?`;ex=`${p.replace('?',String(ans))}입니다.`}}else if(s.grade===2){const x=a+10,y=b+10;ans=s.topic===1?(a%8+2)*b:x+y;p=s.topic===1?`${a%8+2} × ${b} = ?`:`${x} + ${y} = ?`;ex=`${p.replace('?',String(ans))}입니다.`}else if(s.grade===3){ans=s.topic===1?a:a*b;p=s.topic===1?`${a*b} ÷ ${b} = ?`:`${a} × ${b} = ?`;ex=`${a} × ${b} = ${a*b}이므로 답은 ${ans}입니다.`}else if(s.grade===4&&s.topic===0){ans=a*1000+b*100;p=`${a*1000} + ${b*100} = ?`;ex=`같은 자릿수끼리 더하면 ${ans}입니다.`}else if((s.grade===4||s.grade===5)&&s.topic===1){const d=5+b,x=a%d+1,y=b%d+1;const answer=`${x+y}/${d}`;q=question(`${x}/${d} + ${y}/${d}를 계산하세요. (약분하지 않은 값)`,answer,[`${x+y}/${d*2}`,`${x*y+1}/${d+1}`,`${x+y+1}/${d}`],`분모 ${d}는 그대로 두고 분자 ${x}와 ${y}를 더해요.`);if(!seen.has(q.prompt)){seen.add(q.prompt);out.push(q)}continue}else if(s.grade===5){ans=a*b;p=`${a}의 ${b}번째 배수는 무엇인가요?`;ex=`${a} × ${b} = ${ans}입니다.`}else if(s.topic===0){const total=b*100,part=a*b;ans=a;p=`전체 ${total}개 중 ${part}개는 전체의 몇 %인가요?`;ex=`${part} ÷ ${total} × 100 = ${ans}이므로 ${ans}%입니다.`}else{ans=a/10;p=`${(a*b/10).toFixed(1)} ÷ ${b} = ?`;ex=`${ans} × ${b} = ${(a*b/10).toFixed(1)}이므로 답은 ${ans}입니다.`}q=question(s.level===3?`${name}가 풀고 있는 식이에요. 알맞은 수를 골라 주세요.\n${p}`:p,String(ans),[String(ans+1),String(ans+2),String(Math.max(0,ans-1))],ex)}
else if(s.subject==='국어'){const item=['책','그림책','동화책','시집','만화책'][i%5],place=['도서관','교실','집','공원','독서실'][Math.floor(random()*5)];if(s.grade<3){q=question(s.topic===0?`${name}는 어디에서 책을 읽었나요?`:`글에서 ${name}가 한 행동은 무엇인가요?`,s.topic===0?place:'책 읽기',s.topic===0?['운동장','바닷가','수영장']:['공 차기','노래 부르기','밥 먹기'],'글에 나온 장소와 행동을 찾아 읽어 보세요.',`${name}는 ${place}에서 ${item}을 읽었습니다.`)}else if(s.grade<5){const reason=['비가 내려서','날씨가 추워서','바람이 강하게 불어서'][i%3];const indoor=['도서관','교실','집','독서실'][i%4];q=question(s.topic===0?'글의 내용과 일치하는 것은 무엇인가요?':`${name}가 실내에 머문 까닭은 무엇인가요?`,s.topic===0?'실내에서 책을 읽었다':reason,s.topic===0?['밖에서 축구를 했다','바다에 갔다','자전거를 탔다']:['배가 고파서','책이 없어서','친구가 불러서'],'글에 제시된 원인과 행동을 연결해 보세요.',`${reason} ${name}는 ${indoor} 안에 머물렀습니다. ${name}는 가져온 ${item}을 읽었습니다.`)}else{q=question(s.topic===0?'글쓴이의 주장에 해당하는 것은 무엇인가요?':'글쓴이는 어떤 활동을 중요하게 생각하나요?',s.topic===0?'책 읽는 습관을 기르자':'꾸준히 책 읽기',['책은 읽지 않아도 된다','독서는 언제나 지루하다','그림책만 읽어야 한다'],'책 읽기의 장점을 근거로 독서 습관을 권하고 있어요.',`${name}는 ${place}에서 ${item}을 읽으며 새로운 표현을 배웠습니다. 책을 읽으면 여러 생각을 만날 수 있습니다. 매일 조금씩 책을 읽는 습관을 기르면 좋겠습니다.`)}}
else if(s.subject==='영어'){const w=words[(out.length+day*3)%words.length];q=question(s.topic===0?`'${w[0]}'의 뜻은 무엇인가요?`:`다음 문장에서 '${w[0]}'의 뜻을 고르세요.`,w[1],shuffle(words.filter(x=>x!==w),random).slice(0,3).map(x=>x[1]),`${w[0]}은(는) '${w[1]}'라는 뜻이에요.`,s.topic===0?'':`I can see ${'aeiou'.includes(w[0][0])?'an':'a'} ${w[0]}.`)}
else{const bank=banks[s.subject][s.topic];const row=bank[(out.length+day*3)%bank.length];const reverse=out.length>=bank.length;const others=shuffle(bank.filter(x=>x!==row),random).slice(0,3);q=reverse?question(`복습 · ${row[0]}은(는) 무엇인가요?`,row[1],row.slice(2),`${row[0]}에 해당하는 답은 '${row[1]}'입니다.`):question(`${row[0]}은(는) 무엇인가요?`,row[1],row.slice(2),`${row[0]}에 해당하는 답은 '${row[1]}'입니다.`)}
const key=q.prompt+q.passage;if(!seen.has(key)){seen.add(key);out.push(q)}}return out}


